- name: update yum packages
  yum: 
    list: updates 
    update_cache: true

- name: install git
  become: yes
  yum:
    name: git
    state: latest

# Ruby 설치
- name: install ruby
  become: yes
  yum:
    name: ruby
    state: latest

- name: set Asia/Seoul timezone
  become: yes
  timezone:
    name: Asia/Seoul
